name: todo2_client
version: 1.0.0

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  messaging_sdk:
    hosted:
      name: messaging_sdk
      url: https://pub.workiva.org
    version: ^3.5.4
  over_react: ^3.5.0
  todo2_sdk:
    git:
      url: git@github.com:thomasmaloney-wk/todo2-sdk.git
  uuid: ">=1.0.3 <2.0.0"
  w_session:
    hosted:
      name: w_session
      url: https://pub.workiva.org
    version: ^6.68.0
  w_flux: ^2.10.4
  w_module: ^2.0.10
  wdesk_sdk:
    hosted:
      name: wdesk_sdk
      url: https://pub.workiva.org
    version: ^2.206.2
  web_skin_dart:
    hosted:
      name: web_skin_dart
      url: https://pub.workiva.org
    version: ^2.45.2

dev_dependencies:
  build_runner: ^1.7.1
  build_web_compilers: ^2.5.1
  dart_dev: ^3.2.1
  dart_dev_workiva:
    hosted:
      name: dart_dev_workiva
      url: https://pub.workiva.org
    version: ^1.0.0
  dart_style: ^1.3.3
  mockito: '>=3.0.0 <5.0.0'
  over_react_format:
    hosted:
      name: over_react_format
      url: https://pub.workiva.org
    version: ^3.0.0
  over_react_test: ^2.9.0
  react: ^5.1.1
  w_test_tools:
    hosted:
      name: w_test_tools
      url: https://pub.workiva.org
    version: ^1.1.4
  test: ^1.8.0