#!/bin/bash
# This file is generated by the Wdesk SDK. Please see the README for more information.

# Configure environment variables set by default in Admiral
ENV_JS="
workiva.wdesk.environment = {
  LOCAL_HARBOUR_HOST: '$LOCAL_HARBOUR_HOST',
  HARBOUR_SERVICE_PREFIX: '$HARBOUR_SERVICE_PREFIX',
  GIT_BRANCH: '$GIT_BRANCH',
  GIT_COMMIT: '$GIT_COMMIT',
  IAM_HOST: '$IAM_HOST',
  MSG_FRONTEND_URL: '$MSG_FRONTEND_URL',
  STATIC_ASSET_PREFIX: '$STATIC_ASSET_PREFIX',
  VESSEL_URL: '$VESSEL_URL',"

# Configure variables that can be set in a custom INI, whose location is defined
# by the WDESK_SDK_INI environment variable. Note that these variables can still
# be overridden by environment variables.
#   For more info: http://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
if [ ! -z ${WDESK_SDK_INI+x} ]
then
  # If the custom ini file exists, read and inject the values from it.
  # Otherwise, log the error.
  if [ -f $WDESK_SDK_INI ]
  then
    echo "Info: reading custom configuration from file $WDESK_SDK_INI"

    # IFS (internal-field-separator) to split lines on "="
    #
    # The second branch of this condition ([ -n "$var" ]) ensures that we read
    # the last line of the file even if it doesn't end in a newline.
    #   For more info: http://stackoverflow.com/questions/12916352/shell-script-read-missing-last-line
    while IFS="= " read var val || [ -n "$var" ]
    do
      # Ignore lines that start with #, they're comments.
      if [[ $var =~ ^[^#].+ ]]
      then
        if [[ ! -z ${!var} ]]
        then
          # If the var we are parsing is set in the env, use it as an override.
          val="${!var}"
        fi
        escaped_val=${val//\'/\\\'}
        ENV_JS+=$'\n  '
        ENV_JS+="$var: '$escaped_val',"
      fi
    done < "$WDESK_SDK_INI" # Iterate over the contents of the custom ini.
  else
    echo "Warning: WDESK_SDK_INI is set but points to a file that does not"\
    "exist ($WDESK_SDK_INI)."
  fi
else
  echo "Info: no custom configuration found (WDESK_SDK_INI)."
fi

ENV_JS+=$'\n};'

# Dump configuration to the log
echo "$ENV_JS"

# Skip writing to the filesystem if WDESK_SDK_TEST is set.
if [ -z $WDESK_SDK_TEST ]
then
  # Augment the environment_settings.js script with these environment values.
  echo -e "$ENV_JS" >> /tmp/app/js/environment_settings.js

  # Support the dart1/dart2 dual build setup by augmenting the other
  # environment_settings.js as well, if available.
  if [ ! -z ${STATIC_ASSET_PREFIX+x} ]
  then
    echo -e "$ENV_JS" >> /tmp/app/$STATIC_ASSET_PREFIX/js/environment_settings.js
  fi
fi
