#!/usr/bin/env bash
# This file is generated by the Wdesk SDK. Please see the README for more information.

set -e
shopt -s extglob

# This script limits what is pushed to the CDN. Only prod assets
# are included in the bundle that is pushed to the CDN.

rm -rf static

# create static/ directory that will be deployed to CDN
mkdir static/

# stage dart packages
cp -RL build/web/packages static/

# stage compiled Dart parts and source maps
cp build/web/*dart*.+(js|js.map) static/

# stage production HTML and JS peripherals (order is important here!)
cp -RL build/web/js static/
cp -RL build/web/prod/* static/

# remove all source files and unneeded assets
find static -type f -name "*.dart" | xargs rm || true
find static -type f -name "*.scss" | xargs rm || true
find static -type f -name "*.psd" | xargs rm || true

# remove some large files/dirs that we know are unused and don't need to be published
rm static/packages/doc_plat_client/src/engine/lib/doc_engine_with_test_addons.js || true
rm static/packages/doc_plat_client/src/engine/lib/doc_engine_with_test_addons.js.map || true
rm static/packages/user_analytics/analytics.json || true
rm -rf static/packages/\$sdk || true
rm -rf static/packages/doc_plat_client/src/text_doc_client/documentation || true
rm -rf static/packages/doc_plat_client/src/datatables/doc || true
