#!/bin/bash
# This file is generated by the Wdesk SDK. Please see the README for more information.

set -e

# Run environment settings script. This augments the environment_settings.js
# file in order to make certain values from the harbour environment available on
# the window.
/inject_environment_variables.sh

# Provide a hook for additional setup prior to starting the nginx server and
# after augmenting the environment_settings.js script.
#   For more info: http://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
if [ ! -z ${WDESK_SDK_BEFORE_NGINX+x} ]
then
  # If the hook file exists, source it. Otherwise, log the error.
  if [ -f $WDESK_SDK_BEFORE_NGINX ]
  then
    . $WDESK_SDK_BEFORE_NGINX
  else
    echo "Warning: WDESK_SDK_BEFORE_NGINX is set but points to a file that"\
    "does not exist ($WDESK_SDK_BEFORE_NGINX)."
  fi
fi

if [ ! -z ${HARBOUR_SERVICE_PREFIX} ]
then
  # Update root paths with PBR prefix if defined.
  sed -i -r "s|\"/(.*)\"|\"$HARBOUR_SERVICE_PREFIX\1\"|" /tmp/app/index.html
  sed -i -r "s|/(service_worker.js)|$HARBOUR_SERVICE_PREFIX\1|" /tmp/app/js/register_service_worker.js || true
  if [ ! -z ${STATIC_ASSET_PREFIX} ]
  then
    sed -i -r "s|\"/(.*)\"|\"$HARBOUR_SERVICE_PREFIX\1\"|" /tmp/app/$STATIC_ASSET_PREFIX/index.html
  fi
fi

# Substitute template variables for env variables.
# RED-3720: don't send the result to stdout when in use by stdin, that can cause a
# race condition
envsubst '${APP_CONTENT_SECURITY_POLICY} ${DISABLE_STRICT_TRANSPORT_SECURITY} ${STATIC_ASSET_PREFIX}' < /etc/nginx/conf.d/vhost.conf > /etc/nginx/conf.d/vhost.conf.new
mv /etc/nginx/conf.d/vhost.conf.new /etc/nginx/conf.d/vhost.conf

# Test the nginx config.
nginx -t -c /etc/nginx/nginx.conf
if [ $? -ne 0 ]
then
  echo 'fail to pass config test, exiting'
  exit 1
fi

# Fail if APP_CONTENT_SECURITY_POLICY isn't set.
#   For more info: http://stackoverflow.com/questions/3601515/how-to-check-if-a-variable-is-set-in-bash
if [ -z ${APP_CONTENT_SECURITY_POLICY+x} ]
then
  echo "APP_CONTENT_SECURITY_POLICY is *NOT* set"
  exit 1
fi

# Start the nginx server.
nginx
