// This file is generated by the Wdesk SDK. Please see the README for more information.
var drawerLoadingScreen = '';
var richLoadingScreen = '';
var workspacesSwitcherLoadingScreen = '';

var richRouteSegments = [];

var isRich = false;
for (var i = 0; i < richRouteSegments.length; i++) {
  var routeWithQuestionMark = '/' + richRouteSegments[i] + '?';
  var routeWithTrailingSlash = '/' + richRouteSegments[i] + '/';
  var routeAtEndOfUrl = '/' + richRouteSegments[i];
  var url = window.location.href;

  if (url.indexOf(routeWithQuestionMark) !== -1
    || url.indexOf(routeWithTrailingSlash) !== -1
    || url.indexOf(routeAtEndOfUrl, url.length - routeAtEndOfUrl.length) !== -1) {
    isRich = true;
    break;
  }
}

setCorrectLoadingHtml(isRich);

function setCorrectLoadingHtml(isRich) {
  var workspaceColor;
  if (window.hasOwnProperty('workiva')) {
    workspaceColor = window.workiva.wdesk.workspaceColor;
  } else {
    var input = document.getElementById('workspace_color');
    if (input) {
      workspaceColor = input.value;
    }
  }

  if (isRich) {
    document.getElementById('shell-container').innerHTML = richLoadingScreen;
    if (workspaceColor) {
      showWorkspaceColorLoadingOverlay(workspaceColor,
          ['wls-exp__rich-logo-container', 'wls-exp__loading-bar-container'], isRich);
    }
  } else {
    document.getElementById('shell-container').innerHTML = drawerLoadingScreen;
    if (workspaceColor) {
      showDrawerLoadingOverlay(workspaceColor);
    }
  }
}

function showWorkspaceColorLoadingOverlay(workspaceId, listOfClasses, isRich) {
  var div = document.getElementById('loading-overlay') || document.createElement('div');
  div.id = 'loading-overlay';
  div.innerHTML = isRich ? richLoadingScreen : workspacesSwitcherLoadingScreen;
  div.style.cssText = 'position: absolute; height: 100%; width: 100%; top: 0; left: 0; display: block; z-index: 2000;';

  // Add appropriate classnames to given list of classes to augment with workspace color
  listOfClasses.forEach(function (className) {
    var logo = div.getElementsByClassName(className)[0];
    logo.className += ' wksp-switcher__header--presence-bg-' + workspaceId;
  });

  document.body.appendChild(div);
}


function showDrawerLoadingOverlay(workspaceId) {
  showWorkspaceColorLoadingOverlay(workspaceId, ['wls-exp__drawer-header'], false);
}

function hideDrawerLoadingOverlay() {
  var div = document.getElementById('loading-overlay');
  if(div) {
    div.style.display = 'none';
    div.innerHTML = '';
  }
}

window = window || {};

window.overlayManager = {
    'showDrawerLoadingOverlay': showDrawerLoadingOverlay,
    'hideDrawerLoadingOverlay': hideDrawerLoadingOverlay
};
